# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
   push:
    branches: [ master ]
jobs:
  build:
   
    runs-on: ubuntu-latest
   
    steps:
        

    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        if: "!contains(github.event.head_commit.message, 'upload')"
        wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.3.0-Linux-x86_64.sh -O ~/anaconda.sh 
        /bin/bash ~/anaconda.sh -b -p /opt/conda 
        PATH=/opt/conda/bin:$PATH
        python3.6 -m pip install lxml 
        python3.6 -m pip install requests
        python3.6 -m pip install setuptools wheel twine
        
        
        python3.6 upload.py
